### ISSUE TITLE
math.hppを実装

### ISSUE THREAD

**Issue by nu50218** [monkukui/ac-library-go#10]

**Comment by monkukui** [comment]
これやろうと思います。
@nu50218 

#5

**Comment by monkukui** [comment]
ちょっとつらくなってきたので、協力を仰ぎたいです。

### つらい点１、C++ の `constexpr` に代替できる機能が Go にあるかがわからない

ac-library の `internal_math.hpp` では、あらゆる関数が `constecpr` になっています。
https://github.com/atcoder/ac-library/blob/master/atcoder/internal_math.hpp#L16

Go でこれを表現する方法があったら教えてください。

### つらい点 2、`int128` がない
ac-library では、`int128` 型を使用しています。
https://github.com/atcoder/ac-library/blob/master/atcoder/internal_math.hpp#L55-L56

**Comment by nu50218** [comment]
**C++ の constexpr に代替できる機能が Go にあるかがわからない**

constexprはないはずですが、実行時に計算させればよいかと思います

**int128 がない**

やりたいことは乗算の上位64bitをとってきたいだけなので、なにか上手い方法がありそうですが、、、
> 最初の 2 つの引数で渡された 2 つの 64 ビット符号なし整数を乗算し、その積の上位 64 ビットを HighProduct の指す 64 ビットの符号なし整数に格納して、積の下位 64 ビットを返します。
https://docs.microsoft.com/ja-jp/cpp/intrinsics/umul128?view=vs-2019

**Comment by nu50218** [comment]
調べたら`_umul128`と同じような関数が標準パッケージに有りました！
https://golang.org/pkg/math/bits/#Mul64

**Comment by nu50218** [comment]
Fixed by #26
