### ISSUE TITLE
scc.hppを実装

### ISSUE THREAD

**Issue by nu50218** [monkukui/ac-library-go#14]

**Comment by aruaru0** [comment]
勉強を兼ねてACLを移植していますが、こちらに貢献できればと思います。
SCCをgo言語に移植しましたので、以下のリポジトリからこちらに持って行ってもらえれば幸いです。
一応、atcoderのジャッジでACを確認しています

https://github.com/aruaru0/go-atcoder-lib

プログラム的には、C＋＋からのベタ移植です。内部的にテンプレートなどがありましたがその辺りは適当に移植しています。
使い方は、本家と似た感じで使えるかと思います。

違いとしては、goの慣例に合わせて関数名の頭文字が大文字であることと、add_edgeではなくAddEdgeに変更しています。

**Comment by monkukui** [comment]
@aruaru0 コメントありがとうございます！
大変ありがたいです！
こちらのリポジトリにプルリクエストを送っていただくことは可能でしょうか？
その際、レビュアーを @monkukui と @nu50218 にしてもらえると良いです！

難しそうであれば、aruaru0 さんのコードを参考にしつつ、こちらで実装します！

**Comment by aruaru0** [comment]
レビュアー設定が分からなかったのでプルリクエストだけ送りました。確認ください。

**Comment by nu50218** [comment]
設定で自動でレビュアー振られるようにしたので大丈夫です🙆‍♂️
