### ISSUE TITLE
segtree.hppを実装

### ISSUE THREAD

**Issue by nu50218** [monkukui/ac-library-go#15]

**Comment by monkukui** [comment]
抽象化されたライブラリにするためには、Goのジェネリクスを待つしかないですかね
流石に `int` 型に限定したライブラリを作るのは意味がない気がします。

@nu50218

**Comment by nu50218** [comment]
interface{}を使わないようにしたいということならそうだと思います。
container/heapパッケージでも[Interface](https://golang.org/pkg/container/heap/#Interface)型を実装してもらって受け取る形になっていて、interface{}を使っています🥺
[sort.Interface](https://golang.org/pkg/sort/#Interface)型みたいにうまくできればいいんですが、、、

**Comment by monkukui** [comment]
interface{} を使って実装する方針がいいですね。
何か問題がなければその方向で行きましょうか。

**Comment by monkukui** [comment]
ちょっと手をつけてみます
