### ISSUE TITLE
string.hppを実装

### ISSUE THREAD

**Issue by nu50218** [monkukui/ac-library-go#16]

**Comment by monkukui** [comment]
@nu50218 これやります

**Comment by nu50218** [comment]
ありがとうございます！
文字列アルゴリズムは、有名なやつは結構標準ライブラリで提供されている印象があるので、一度調べてからやると楽になりそうです。
たとえばSuffix Arrayとか。
https://golang.org/pkg/index/suffixarray/

**Comment by monkukui** [comment]
Suffix Array 標準であるのか...
それを使うことにすると、実装量がかなり少なくなりそうです

**Comment by monkukui** [comment]
Go の `suffixarray` は、SA-IS で実装されていそうなので、良さそう

**Comment by monkukui** [comment]
参考
https://future-architect.github.io/articles/20200807/

**Comment by monkukui** [comment]
Go には関数オーバーロードの機能がないので、
```
(1) vector<int> suffix_array(string s)
(2) vector<int> suffix_array<T>(vector<T> s)
(3) vector<int> suffix_array(vector<int> s, int upper)
```

のようなことができない。
interface をうまく使って（本家と少し実装スタイルが異なるけど）実装する方針を考えてみます。
@nu50218

**Comment by monkukui** [comment]
うーん、ただの関数として定義したいなら、名前を変えるしかないですかね？
struct のメソッドにするなら、interface 使ってよしなにできそうですが

**Comment by monkukui** [comment]
関数名案
```Go
// SA
func SuffixArray(s string) []int
func SuffixArrayInt(s []int) []int
func SuffixArrayWithUpper(s []int, upper int) []int

// LCP
func LcpArray(s string, []int sa) []int
func LcpArrayInt(s []int, []int sa) []int

// Z
func ZAlgorithm(s string) []int
func ZAlgorithmInt(s []int) []int
```

**Comment by monkukui** [comment]
標準で提供されている `suffixarray` は、文字列検索の用途でしか使えなさそうです。
export されている主な関数は、

- `func (x *Index) Lookup(s []byte, n int) (result []int)`（文字列がマッチするか検索する）
- `func (x *Index) FindAllIndex(r *regexp.Regexp, n int) (result [][]int)`（正規表現がマッチするか検索する）

の二つです。

競プロ的には、Suffix の辞書順でソートされた index からなる配列が必要になることが多く、また、それを用いて LCP 配列を構築する必要もあります。
標準パッケージではそれらの情報が export されていないため、使用できません。

やっぱり、自前で実装する必要がありそうですかね...

@nu50218

**Comment by nu50218** [comment]
あら、、、
自前でやらなきゃいけないっぽいですね…🥺

**Comment by monkukui** [comment]
とりあえず、ZAlgorithm を実装しました
https://github.com/monkukui/ac-library-go/pull/27
